# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  # Install ICU and CMake (TODO: install 32bit version as well)
  - call C:\msys64\usr\bin\pacman.exe --noconfirm -Sy mingw-w64-x86_64-icu mingw-w64-x86_64-cmake icu icu-devel
  # Install RTools
  - ps: |
        if (!(Test-Path "C:\Rtools")) {
          InstallRtools
        }
  # Install boost
  - appveyor DownloadFile https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
  - tar xzf boost_1_68_0.tar.gz
  - del boost_1_68_0.tar.gz
  - cd boost_1_68_0/
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;%PATH%
  - call .\bootstrap.bat --prefix=C:\msys64\mingw64 --with-libraries=regex,filesystem,system
  - call .\b2 -a define=_GLIBCXX_USE_CXX11_ABI=0 include=C:\msys64\mingw64\include -sICU_LINK="-licuuc -licudt -licuin" link=shared variant=release install headers

build_script:
  - set 'CC=C:\Rtools\mingw_64\bin\gcc'
  - set 'CXX=C:\Rtools\mingw_64\bin\g++'
  - appveyor DownloadFile http://archive.apache.org/dist/arrow/arrow-0.11.1/apache-arrow-0.11.1.tar.gz
  - tar xzf apache-arrow-0.11.1.tar.gz
  - del apache-arrow-0.11.1.tar.gz
  - cd apache-arrow-0.11.1/cpp
  - mkdir build
  - cd build
  - call C:\msys64\mingw64\bin\cmake.exe -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release .. ^
      -DARROW_BUILD_TESTS=FALSE ^
      -DARROW_WITH_SNAPPY=FALSE ^
      -DARROW_WITH_ZSTD=FALSE ^
      -DARROW_WITH_LZ4=FALSE ^
      -DARROW_JEMALLOC=FALSE ^
      -DARROW_BUILD_STATIC=TRUE ^
      -DARROW_BOOST_VENDORED=FALSE ^
      -DARROW_BOOST_USE_SHARED=FALSE ^
      -DARROW_WITH_ZLIB=FALSE ^
      -DARROW_WITH_BROTLI=FALSE

on_failure:
  - appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/boost_1_68_0/bootstrap.log

cache:
  - C:\Rtools
